"""
MODULE 8: Real-Time Alerting & Action Engine
Mobile Money Fraud Detection System - Zambia
alerts.py

Persists alert records generated by the scoring pipeline and provides
query functions for the dashboard notification layer.

Alert types:
    - BLOCK       : Transaction blocked (score ≥ 60, High risk)
    - STEP_UP     : Step-up authentication required (score 30–59, Medium risk)
    - REAL_TIME   : Informational real-time alert (any flagged transaction)

Linked to the use cases:
    - "Send Real-Time Alert" (<<include>> from Score Transaction Risk)
    - "Block / Step-Up Auth" (<<include>> from Score Transaction Risk)
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import Column, DateTime, Float, Integer, String, Boolean, Text
from sqlalchemy.orm import Session

from db_config import Base, get_engine


# ─────────────────────────────────────────────
# ORM MODEL
# ─────────────────────────────────────────────

class AlertRecord(Base):
    __tablename__ = "alert_records"

    alert_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    txn_id = Column(String(36), nullable=False, index=True)
    alert_type = Column(String(20), nullable=False)    # BLOCK, STEP_UP_AUTH, REAL_TIME
    severity = Column(String(10), nullable=False)      # High, Medium, Low
    risk_score = Column(Float, nullable=False)
    message = Column(Text, nullable=False)
    recipient_role = Column(String(20), default="analyst")
    is_read = Column(Boolean, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    resolved_at = Column(DateTime, nullable=True)
    resolved_by = Column(String(36), nullable=True)    # user_id of resolver


# ─────────────────────────────────────────────
# ACTION DETERMINATION
# ─────────────────────────────────────────────

def determine_action(risk_score: float, risk_level: str) -> str:
    """
    Map a risk score / level to a recommended action.
    Returns one of: 'BLOCK', 'STEP_UP_AUTH', 'ALLOW'.

    Tier mapping (Table 3.1):
      Critical (85–100) → BLOCK
      High     (60–84)  → BLOCK
      Medium   (30–59)  → STEP_UP_AUTH
      Low      (< 30)   → ALLOW
    """
    if risk_level in ("Critical", "High") or risk_score >= 60:
        return "BLOCK"
    elif risk_score >= 30 or risk_level == "Medium":
        return "STEP_UP_AUTH"
    else:
        return "ALLOW"


# ─────────────────────────────────────────────
# ALERT MESSAGE TEMPLATES
# ─────────────────────────────────────────────

_ALERT_MESSAGES = {
    "BLOCK": (
        "🚨 TRANSACTION BLOCKED — Risk score {score:.0f}/100 ({level}). "
        "Transaction {txn_id} has been automatically blocked pending analyst review. "
        "Reason codes: {reasons}."
    ),
    "STEP_UP_AUTH": (
        "⚠️ STEP-UP AUTH REQUIRED — Risk score {score:.0f}/100 ({level}). "
        "Transaction {txn_id} requires additional identity verification before processing. "
        "Reason codes: {reasons}."
    ),
    "REAL_TIME": (
        "ℹ️ REAL-TIME ALERT — Risk score {score:.0f}/100 ({level}). "
        "Transaction {txn_id} flagged for review. "
        "Reason codes: {reasons}."
    ),
    "ALLOW": (
        "✅ Transaction {txn_id} scored {score:.0f}/100 ({level}). "
        "No action required."
    ),
}


# ─────────────────────────────────────────────
# CREATE / QUERY ALERTS
# ─────────────────────────────────────────────

def create_alert(
    txn_id: str,
    risk_score: float,
    risk_level: str,
    reason_codes: list[str],
    action: str,
) -> Optional[AlertRecord]:
    """
    Create and persist an alert record for a scored transaction.
    Only creates alerts for BLOCK and STEP_UP_AUTH actions (not ALLOW).
    Returns the AlertRecord or None if no alert was needed.
    """
    if action == "ALLOW":
        return None

    alert_type = action if action in ("BLOCK", "STEP_UP_AUTH") else "REAL_TIME"
    reasons_str = "; ".join(reason_codes[:3]) if reason_codes else "No specific indicators"
    message = _ALERT_MESSAGES.get(alert_type, _ALERT_MESSAGES["REAL_TIME"]).format(
        score=risk_score,
        level=risk_level,
        txn_id=txn_id[:24] + "..." if len(txn_id) > 24 else txn_id,
        reasons=reasons_str,
    )

    alert = AlertRecord(
        alert_id=str(uuid.uuid4()),
        txn_id=txn_id,
        alert_type=alert_type,
        severity=risk_level,
        risk_score=risk_score,
        message=message,
        recipient_role="analyst",
        is_read=False,
        created_at=datetime.now(timezone.utc),
    )

    engine = get_engine()
    try:
        with Session(engine) as session:
            session.add(alert)
            session.commit()
            session.refresh(alert)
        return alert
    except Exception:
        return None


def get_unread_alerts(limit: int = 50) -> list[dict]:
    """Return the most recent unread alerts as a list of dicts."""
    engine = get_engine()
    with Session(engine) as session:
        records = (
            session.query(AlertRecord)
            .filter_by(is_read=False)
            .order_by(AlertRecord.created_at.desc())
            .limit(limit)
            .all()
        )
        return [
            {
                "alert_id": r.alert_id,
                "txn_id": r.txn_id,
                "alert_type": r.alert_type,
                "severity": r.severity,
                "risk_score": r.risk_score,
                "message": r.message,
                "created_at": r.created_at.isoformat() if r.created_at else "",
            }
            for r in records
        ]


def get_alert_counts() -> dict:
    """Return counts of unread alerts by severity."""
    engine = get_engine()
    with Session(engine) as session:
        total = session.query(AlertRecord).filter_by(is_read=False).count()
        blocks = (
            session.query(AlertRecord)
            .filter_by(is_read=False, alert_type="BLOCK")
            .count()
        )
        stepups = (
            session.query(AlertRecord)
            .filter_by(is_read=False, alert_type="STEP_UP_AUTH")
            .count()
        )
        return {
            "total_unread": total,
            "blocks": blocks,
            "step_ups": stepups,
        }


def mark_alert_read(alert_id: str, resolved_by: str | None = None) -> bool:
    """Mark an alert as read/resolved."""
    engine = get_engine()
    with Session(engine) as session:
        alert = session.query(AlertRecord).filter_by(alert_id=alert_id).first()
        if not alert:
            return False
        alert.is_read = True
        alert.resolved_at = datetime.now(timezone.utc)
        alert.resolved_by = resolved_by
        session.commit()
        return True


def mark_all_read(resolved_by: str | None = None) -> int:
    """Mark all unread alerts as read. Returns count of alerts marked."""
    engine = get_engine()
    with Session(engine) as session:
        unread = session.query(AlertRecord).filter_by(is_read=False).all()
        count = len(unread)
        for alert in unread:
            alert.is_read = True
            alert.resolved_at = datetime.now(timezone.utc)
            alert.resolved_by = resolved_by
        session.commit()
        return count


def get_alerts_for_txn(txn_id: str) -> list[dict]:
    """Return all alerts associated with a specific transaction."""
    engine = get_engine()
    with Session(engine) as session:
        records = (
            session.query(AlertRecord)
            .filter_by(txn_id=txn_id)
            .order_by(AlertRecord.created_at.desc())
            .all()
        )
        return [
            {
                "alert_id": r.alert_id,
                "alert_type": r.alert_type,
                "severity": r.severity,
                "risk_score": r.risk_score,
                "message": r.message,
                "is_read": r.is_read,
                "created_at": r.created_at.isoformat() if r.created_at else "",
                "resolved_at": r.resolved_at.isoformat() if r.resolved_at else None,
            }
            for r in records
        ]


# ─────────────────────────────────────────────
# CUSTOMER-FACING NOTIFICATIONS (FR gap #8)
# Actor 1 "Mobile money user ... receives alerts"
# ─────────────────────────────────────────────

import logging as _logging
_notif_logger = _logging.getLogger("fraud_notifications")

# Customer-facing message templates
_CUSTOMER_MESSAGES = {
    "BLOCK": (
        "SECURITY ALERT: Your Mobile Money transaction of K{amount:.0f} has been "
        "temporarily held due to unusual activity. If this was you, please call "
        "our 24/7 helpline: 100. Ref: {txn_ref}"
    ),
    "STEP_UP_AUTH": (
        "VERIFICATION REQUIRED: To complete your transaction, please dial *100# "
        "and enter your security PIN within 10 minutes. Ref: {txn_ref}"
    ),
}


def send_customer_notification(
    txn_id: str,
    hashed_msisdn: str,
    action: str,
    risk_level: str,
    amount: float = 0.0,
) -> bool:
    """
    Send an outbound notification to the mobile money customer when a
    transaction is blocked or held for step-up authentication (FR gap #8).

    Current implementation: persists a CustomerNotification DB record
    and logs a structured message (PENDING status).

    Production integration point:
        Replace the stub below with an Africa's Talking or Twilio SMS call.
        Example (Africa's Talking):

            import africastalking
            africastalking.initialize(os.getenv('AT_USERNAME'), os.getenv('AT_API_KEY'))
            sms = africastalking.SMS
            # Reverse-hash MSISDN via secure lookup (requires plain-text store)
            sms.send(message, ["+260XXXXXXXXX"])

    Parameters
    ----------
    txn_id        : transaction being held
    hashed_msisdn : HMAC-hashed MSISDN of the sender (for audit; cannot be reversed)
    action        : 'BLOCK' | 'STEP_UP_AUTH'
    risk_level    : 'Low' | 'Medium' | 'High' | 'Critical'
    amount        : transaction amount in ZMW (for the message template)
    """
    if action not in ("BLOCK", "STEP_UP_AUTH"):
        return False  # No notification for ALLOW actions

    message_type = action
    txn_ref = txn_id[:12].upper()
    message_body = _CUSTOMER_MESSAGES.get(action, "").format(
        amount=amount, txn_ref=txn_ref
    )

    # 1. Persist audit record
    try:
        from db_config import CustomerNotification, get_engine
        from sqlalchemy.orm import Session
        with Session(get_engine()) as s:
            notif = CustomerNotification(
                notification_id=str(uuid.uuid4()),
                txn_id=txn_id,
                hashed_msisdn=hashed_msisdn,
                message_type=message_type,
                channel="SMS",
                status="PENDING",   # SENT once gateway confirms delivery
                created_at=datetime.now(timezone.utc),
            )
            s.add(notif)
            s.commit()
    except Exception as e:
        _notif_logger.error(f"[notification] DB write failed for txn {txn_id}: {e}")

    # 2. Log structured notification (replace with SMS gateway call in production)
    _notif_logger.info(
        f"[notification] txn={txn_id} msisdn_hash={hashed_msisdn[:8]}... "
        f"action={action} level={risk_level} message='{message_body[:60]}...'"
    )

    # 3. TODO: SMS gateway dispatch
    # Uncomment and configure when Africa's Talking / Twilio credentials are available:
    #
    # try:
    #     _send_via_gateway(hashed_msisdn, message_body)
    #     _update_notification_status(txn_id, "SENT")
    # except Exception as e:
    #     _update_notification_status(txn_id, "FAILED")
    #     _notif_logger.error(f"[notification] Gateway dispatch failed: {e}")

    return True
